import test from 'node:test';import assert from 'node:assert/strict';import {BuildWorld,WORLD_KEY,worldPicture,nextWorldReward,rewardTrail} from './build-world.mjs';
const memory=()=>{const m=new Map();return{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k),m};};
test('construction is cumulative, durable and idempotent across replay/reload',()=>{const store=memory();store.setItem('legacy','untouched');const w=new BuildWorld(store);assert.equal(w.count,0);assert.ok(w.award('basic:1','mat'));assert.equal(w.award('basic:1','mat'),false);const id=w.startComplex();assert.equal(id,'complex:1');assert.ok(w.award(id,'thought'));const copy=new BuildWorld(store);assert.equal(copy.count,2);assert.equal(copy.award(id,'thought'),false);assert.equal(copy.startComplex(),'complex:2');assert.equal(store.getItem('legacy'),'untouched');assert.equal(store.m.size,2);});
test('a cancelled/unfinished complex attempt awards nothing',()=>{const w=new BuildWorld(memory());const id=w.startComplex();assert.equal(w.count,0);assert.equal(w.startComplex(),'complex:2');assert.equal(w.count,0);assert.ok(w.award(id,'thought'));assert.equal(w.award(id,'thought'),false);assert.equal(w.award(null,'thought'),false);});
test('stale tabs cannot overwrite newer owned machines',()=>{const s=memory(),a=new BuildWorld(s),b=new BuildWorld(s);assert.ok(a.award('basic:1','mat'));const raw=s.getItem(WORLD_KEY);assert.equal(b.award('basic:2','sat'),false);assert.equal(b.problem,'conflict');assert.equal(s.getItem(WORLD_KEY),raw);});
test('corrupt/future collections stay untouched, with no automatic reset',()=>{for(const raw of ['broken',JSON.stringify({version:2,next:1,claims:[]}),JSON.stringify({version:1,next:1,claims:[{id:'complex:1',word:'thought'}]})]){const s=memory();s.setItem(WORLD_KEY,raw);const w=new BuildWorld(s);assert.equal(w.problem,'invalid');assert.equal(w.startComplex(),null);assert.equal(w.award('basic:1','mat'),false);assert.equal(s.getItem(WORLD_KEY),raw);}});
test('denied storage is visibly temporary but construction still works in memory',()=>{const w=new BuildWorld({getItem(){throw Error('denied')},setItem(){throw Error('denied')}});assert.equal(w.problem,'unavailable');const id=w.startComplex();assert.ok(w.award(id,'thought'));assert.equal(w.count,1);assert.equal(w.problem,'unavailable');});
test('owned machines add characters, greenery, towers and an airship at milestones',()=>{const w=new BuildWorld(memory());for(let i=1;i<=6;i++)w.award('basic:'+i,i%2?'mat':'sat');const svg=worldPicture(w);assert.equal((svg.match(/class="owned-machine"/g)||[]).length,6);assert.equal((svg.match(/class="owned-robot"/g)||[]).length,3);assert.equal((svg.match(/class="owned-garden"/g)||[]).length,2);assert.match(svg,/owned-tower/);assert.match(svg,/owned-airship/);});

test('old completed basic rounds become owned once, excluding the active unfinished round',()=>{const store=memory();const w=new BuildWorld(store);assert.ok(w.importCompletedRounds(4));assert.deepEqual(w.state.claims,[{id:'basic:1',word:'mat'},{id:'basic:2',word:'sat'},{id:'basic:3',word:'mat'}]);assert.equal(w.importCompletedRounds(4),false);assert.equal(w.count,3);const copy=new BuildWorld(store);assert.equal(copy.importCompletedRounds(4),false);assert.equal(copy.count,3);});

test('next possession is visible before building and advances only with owned claims',()=>{const w=new BuildWorld(memory());assert.deepEqual(nextWorldReward(0),{kind:'machine',start:0,target:1});assert.match(rewardTrail(w),/data-next-reward="machine"/);w.startComplex();assert.equal(nextWorldReward(w.count).kind,'machine');for(let i=1;i<=6;i++){w.award('basic:'+i,'mat');assert.equal(nextWorldReward(w.count).kind,['robot','garden','tower','airship','airship','robot'][i-1]);}assert.equal(nextWorldReward(5).target,6);assert.equal(nextWorldReward(7).target,8);assert.equal(nextWorldReward(8).target,9);});
test('full city includes space to grow without pretending future machines are owned',()=>{const w=new BuildWorld(memory());w.award('basic:1','mat');const svg=worldPicture(w);assert.equal((svg.match(/class="owned-machine"/g)||[]).length,1);assert.equal((svg.match(/class="future-foundation"/g)||[]).length,3);assert.match(svg,/viewBox="0 0 420 520"/);});
