import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {setupComplexDemo} from './complex-demo.mjs';import {BuildWorld,WORLD_KEY} from './build-world.mjs';
const {JSDOM}=createRequire(import.meta.url)('jsdom');const tick=()=>new Promise(r=>setTimeout(r,0));
test('whole-word challenge has no automatic answer hints, accepts editable attempts and awards only after whole submission',async()=>{
 const dom=new JSDOM('<main id="app"><div id="word-goal"></div></main>',{url:'https://example.test'});Object.assign(globalThis,{window:dom.window,document:dom.window.document});let audios=[],fail=false,opened=0,closed=0;dom.window.localStorage.setItem('legacy','untouched');const world=new BuildWorld(dom.window.localStorage);
 class Audio{constructor(path){this.path=path;audios.push(this);}play(){return fail?Promise.reject(Error('unavailable')):Promise.resolve();}pause(){this.onpause?.();}removeAttribute(){}load(){}}
 const demo=setupComplexDemo({world,random:()=>0,createAudio:p=>new Audio(p),beforeOpen:()=>opened++,afterClose:()=>closed++});const b=label=>document.querySelector(`button[aria-label="${label}"]`);const click=async label=>{assert.ok(b(label),label);b(label).click();await tick();};const end=async()=>{audios.at(-1).onended();await tick();};const parts=()=>[...document.querySelectorAll('.group-part')].map(b=>b.textContent);const panel=()=>document.querySelector('.complex-demo');demo.open();assert.equal(opened,1);assert.equal(panel().querySelector('.thought-meaning'),null);assert.equal(panel().querySelector('.complex-scene'),null);assert.equal(panel().textContent.includes('thought'),false);assert.equal(b('בניית המילה המורכבת'),null);
 fail=true;await click('השמעת המטרה בלי כתיב');assert.match(document.querySelector('[role=alert]').getAttribute('aria-label'),/לא הושלם/);assert.equal(b('בניית המילה המורכבת'),null);fail=false;
 await click('השמעת המטרה בלי כתיב');assert.equal(audios.at(-1).path,'audio/complex-word/thought.wav');assert.equal(b('בניית המילה המורכבת'),null);const cancelled=audios.at(-1);demo.close();cancelled.onended();await tick();demo.open();assert.equal(b('בניית המילה המורכבת'),null);
 await click('השמעת המטרה בלי כתיב');await end();await click('בניית המילה המורכבת');assert.deepEqual([...parts()].sort(),['f','o','ough','ow','t','th']);assert.equal(document.querySelector('.group-target'),null);assert.equal(b('בדיקת הצירוף והפעלת המכונה').disabled,true);const order=parts();
 await click('קבוצת אותיות t');assert.equal(document.querySelector('[role=alert]'),null);assert.equal(panel().dataset.stage,'BUILD');assert.equal(document.querySelector('.assembly').dataset.installed,'1');assert.equal(world.count,0);assert.deepEqual(parts(),order);await click('בדיקת הצירוף והפעלת המכונה');assert.ok(document.querySelector('[role=alert]'));assert.equal(world.count,0);assert.equal(panel().querySelector('.thought-meaning'),null);assert.equal(document.querySelector('.group-target'),null);
 await click('פירוק הצירוף לניסיון חדש');for(const g of ['th','ough','f'])await click('קבוצת אותיות '+g);assert.equal(panel().dataset.stage,'BUILD');assert.equal(document.querySelector('[role=alert]'),null);await click('בדיקת הצירוף והפעלת המכונה');assert.equal(world.count,0);assert.equal(b('השמעת המילה thought'),null);await click('הסרת חלק 3: f');await click('קבוצת אותיות t');assert.equal(panel().dataset.stage,'BUILD');assert.equal(document.querySelector('.assembly').dataset.installed,'3');assert.equal(world.count,0);await click('בדיקת הצירוף והפעלת המכונה');assert.equal(panel().dataset.stage,'DONE');assert.equal(document.querySelector('.assembly').dataset.installed,'4');assert.equal(world.count,1);assert.match(panel().querySelector('.thought-meaning').textContent,/חשב/);
 await click('השמעת המילה thought');assert.equal(audios.at(-1).path,'audio/complex-word/thought.wav');await end();assert.equal(world.count,1);assert.equal(new BuildWorld(dom.window.localStorage).count,1);await click('הדגמה חוזרת');assert.equal(b('בניית המילה המורכבת'),null);assert.equal(panel().querySelector('.thought-meaning'),null);assert.equal(world.count,1);assert.equal(dom.window.localStorage.getItem('legacy'),'untouched');assert.ok(dom.window.localStorage.getItem(WORLD_KEY));demo.close();assert.equal(closed,2);assert.equal(document.getElementById('app').hidden,false);dom.window.close();
});
test('challenge allows longer/wrong constructions without identifying a wrong part or rewarding a matching prefix',async()=>{
 const dom=new JSDOM('<main id="app"><div id="word-goal"></div></main>',{url:'https://example.test'});Object.assign(globalThis,{window:dom.window,document:dom.window.document});let audio;class Audio{constructor(){audio=this;}play(){return Promise.resolve();}pause(){}removeAttribute(){}load(){}}const world=new BuildWorld(dom.window.localStorage);const demo=setupComplexDemo({world,createAudio:()=>new Audio()});const b=label=>document.querySelector(`button[aria-label="${label}"]`);demo.open();b('השמעת המטרה בלי כתיב').click();await tick();audio.onended();await tick();b('בניית המילה המורכבת').click();for(const g of ['th','ough','t','o','f'])b('קבוצת אותיות '+g).click();assert.equal(document.querySelectorAll('.pending-part').length,5);assert.ok([...document.querySelectorAll('.group-part')].every(b=>b.disabled));b('בדיקת הצירוף והפעלת המכונה').click();assert.equal(world.count,0);assert.equal(document.querySelector('.complex-demo').dataset.stage,'BUILD');b('הסרת חלק 5: f').click();assert.ok([...document.querySelectorAll('.group-part')].every(b=>!b.disabled));b('הסרת חלק 4: o').click();assert.equal(world.count,0);b('בדיקת הצירוף והפעלת המכונה').click();assert.equal(world.count,1);dom.window.close();
});
test('recorded thought media and attribution are reproducible',()=>{const wav=readFileSync(new URL('./audio/complex-word/thought.wav',import.meta.url));assert.equal(wav.toString('ascii',0,4),'RIFF');assert.equal(createHash('sha256').update(wav).digest('hex'),'57e081b217588e27e19310651942c98d2fc186fb901133f616b7f1f9e79b5d66');assert.match(readFileSync(new URL('./audio/complex-word/ATTRIBUTION.md',import.meta.url),'utf8'),/CC BY-SA 3.0/);});
