import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {setupComplexDemo} from './complex-demo.mjs';
const {JSDOM}=createRequire(import.meta.url)('jsdom');const tick=()=>new Promise(r=>setTimeout(r,0));
test('thought recorded demo: hidden goal, failed audio, completion gate, groups, meaning, cancellation, no storage',async()=>{
 const dom=new JSDOM('<main id="app"><div id="word-goal"></div></main>',{url:'https://example.test'});Object.assign(globalThis,{window:dom.window,document:dom.window.document});let audios=[],fail=false,opened=0,closed=0;
 class Audio{constructor(path){this.path=path;audios.push(this);}play(){return fail?Promise.reject(Error('unavailable')):Promise.resolve();}pause(){this.onpause?.();}removeAttribute(){}load(){}}
 const demo=setupComplexDemo({createAudio:p=>new Audio(p),beforeOpen:()=>opened++,afterClose:()=>closed++});const b=label=>document.querySelector(`button[aria-label="${label}"]`);const click=async label=>{b(label).click();await tick();};const end=async()=>{audios.at(-1).onended();await tick();};demo.open();assert.equal(opened,1);assert.equal(document.querySelector('.complex-demo').textContent.includes('thought —'),false);assert.equal(b('בניית המילה המורכבת'),null);
 fail=true;await click('השמעת המטרה בלי כתיב');assert.match(document.querySelector('[role=alert]').getAttribute('aria-label'),/לא הושלם/);assert.equal(b('בניית המילה המורכבת'),null);fail=false;
 await click('השמעת המטרה בלי כתיב');assert.equal(audios.at(-1).path,'audio/complex-word/thought.wav');assert.equal(b('בניית המילה המורכבת'),null);const cancelled=audios.at(-1);demo.close();cancelled.onended();await tick();demo.open();assert.equal(b('בניית המילה המורכבת'),null);
 await click('השמעת המטרה בלי כתיב');await end();await click('בניית המילה המורכבת');await click('קבוצת אותיות t');assert.equal(document.querySelector('.group-target').textContent,'th');
 for(const g of ['th','ough','t'])await click('קבוצת אותיות '+g);await click('אדם ישן');assert.equal(b('השמעת המילה thought'),null);await click('אדם חושב');await click('השמעת המילה thought');assert.equal(audios.at(-1).path,'audio/complex-word/thought.wav');await end();assert.equal(dom.window.localStorage.length,0);await click('הדגמה חוזרת');assert.equal(b('בניית המילה המורכבת'),null);demo.close();assert.equal(closed,2);assert.equal(document.getElementById('app').hidden,false);dom.window.close();
});
test('recorded thought media and attribution are reproducible',()=>{const wav=readFileSync(new URL('./audio/complex-word/thought.wav',import.meta.url));assert.equal(wav.toString('ascii',0,4),'RIFF');assert.equal(createHash('sha256').update(wav).digest('hex'),'57e081b217588e27e19310651942c98d2fc186fb901133f616b7f1f9e79b5d66');assert.match(readFileSync(new URL('./audio/complex-word/ATTRIBUTION.md',import.meta.url),'utf8'),/CC BY-SA 3.0/);});
