import {glyph,assemblyPicture,worldPicture,rewardTrail} from './build-world.mjs';
import {AudioPlayer} from './audio-player.mjs';
// Whole-word construction challenge; cosmetics only, never engine mastery/evidence.
export function setupComplexDemo({beforeOpen,afterClose,host=document.body,world,onWorld,createAudio=path=>new Audio(path),random=Math.random}={}){
 const app=document.getElementById('app'),launch=document.createElement('button');launch.className='complex-launch';launch.innerHTML=glyph('puzzle');launch.setAttribute('aria-label','פתיחת הדגמת מילה מורכבת');if(app.querySelector('.tools'))app.querySelector('.tools').append(launch);else app.insertBefore(launch,document.getElementById('word-goal'));
 const panel=document.createElement('section');panel.className='complex-demo';panel.hidden=true;panel.setAttribute('aria-label','אתגר בניית מילה מורכבת');host.append(panel);
 let phase='GOAL',chosen=[],heard=false,busy=false,error='',serial=0,buildId=null,pool=[];
 const audio=new AudioPlayer({paths:{THOUGHT:'audio/complex-word/thought.wav'},create:createAudio});
 function stop(){serial++;busy=false;audio.stop();}
 function newAttempt(){stop();phase='GOAL';chosen=[];heard=false;error='';buildId=world?.startComplex();pool=['th','ough','t','f','ow','o'];for(let i=pool.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}}
 function control(host,label,html,fn,cls='',disabled=false){const b=document.createElement('button');b.setAttribute('aria-label',label);b.innerHTML=html;b.className=cls;b.disabled=disabled;b.onclick=fn;host.append(b);return b;}
 async function speak(){if(busy)return;stop();const token=serial;busy=true;error='';render();const ok=await audio.play('THOUGHT');if(token!==serial)return;busy=false;if(ok)heard=true;else error='השמע לא הושלם. לחצו על הרמקול לנסות שוב.';render();}
 function submit(){if(busy||phase!=='BUILD'||!chosen.length)return;if(chosen.join('')==='thought'){phase='DONE';error='';world?.award(buildId,'thought');}else error='הצירוף אינו מתאים למילה ששמעת. אפשר לשנות חלקים ולהאזין שוב.';render();}
 function render(){
  const previousFocus=panel.contains(document.activeElement)?document.activeElement.getAttribute('aria-label'):null;panel.replaceChildren();panel.dataset.stage=phase;panel.classList.toggle('attempt-error',!!error&&phase==='BUILD');
  const steps=document.createElement('div');steps.className='build-steps';steps.dir='ltr';steps.setAttribute('aria-label','לשמוע, לבנות ולבדוק, לאסוף');const active=phase==='GOAL'?0:phase==='BUILD'?1:2;steps.innerHTML=['sound','build','map'].map((name,i)=>`<span class="${i===active?'current':i<active?'complete':''}">${glyph(name)}</span>${i<2?glyph('next'):''}`).join('');panel.append(steps);
  const bench=document.createElement('div');bench.className='complex-machine';bench.innerHTML=assemblyPicture(phase==='DONE'?4:Math.min(3,chosen.length));panel.append(bench);
  if(phase==='BUILD'){
   const slots=document.createElement('div');slots.className='complex-slots';slots.dir='ltr';slots.setAttribute('aria-label','הצירוף שבנית; נגיעה בחלק מסירה אותו');if(!chosen.length){slots.innerHTML=`<span class="empty-socket">${glyph('build')}</span>`;}else chosen.forEach((g,i)=>control(slots,`הסרת חלק ${i+1}: ${g}`,`<span lang="en">${g}</span><span class="tile-remove" aria-hidden="true">×</span>`,()=>{chosen.splice(i,1);error='';render();},'pending-part',busy));panel.append(slots);
  }
  const sound=control(panel,phase==='DONE'?'השמעת המילה thought':'השמעת המטרה בלי כתיב',(phase==='DONE'?'<span lang="en" dir="ltr">thought</span> ':'')+glyph('sound'),speak,(phase==='DONE'||phase==='GOAL'&&!heard?'primary ':'')+(busy?'listening':''),busy);sound.classList.add('goal-speaker');
  if(phase==='GOAL'&&heard&&!busy)control(panel,'בניית המילה המורכבת',glyph('build')+glyph('next'),()=>{phase='BUILD';error='';render();},'primary demo');
  if(phase==='BUILD'){
   const tray=document.createElement('div');tray.className='complex-choices';tray.dir='ltr';panel.append(tray);for(const g of pool)control(tray,`קבוצת אותיות ${g}`,`<span lang="en">${g}</span>`,()=>{chosen.push(g);error='';render();},'group-part',busy||chosen.length>=5);
   const tools=document.createElement('div');tools.className='challenge-tools';panel.append(tools);control(tools,'בדיקת הצירוף והפעלת המכונה',glyph('power'),submit,'primary run-challenge',busy||!chosen.length);control(tools,'פירוק הצירוף לניסיון חדש',glyph('retry'),()=>{chosen=[];error='';render();},'',busy||!chosen.length);
  }
  if(phase==='DONE'){
   const meaning=document.createElement('div');meaning.className='thought-meaning';meaning.innerHTML='<svg viewBox="0 0 300 170" role="img" aria-label="אדם חושב על פתרון לפאזל"><defs><linearGradient id="thought-card" x2="1" y2="1"><stop stop-color="#345773"/><stop offset="1" stop-color="#182c4b"/></linearGradient></defs><rect x="4" y="4" width="292" height="160" rx="24" fill="url(#thought-card)"/><path d="M41 151Q40 94 77 94Q110 93 123 151" fill="#607fbd"/><circle cx="75" cy="71" r="27" fill="#ffd4af"/><path d="M48 63Q45 23 77 30Q106 28 107 62Q75 36 48 63" fill="#553948"/><path d="M89 78Q103 75 98 86M69 70h3" stroke="#714c47" stroke-width="4" fill="none" stroke-linecap="round"/><path d="M97 143L117 111L95 86" stroke="#ffd4af" stroke-width="12" stroke-linecap="round" fill="none"/><path d="M157 22H262Q282 22 282 42V94Q282 110 264 110H155Q136 110 136 93V42Q136 22 157 22Z" fill="#fff0c8"/><circle cx="125" cy="117" r="7" fill="#fff0c8"/><circle cx="112" cy="124" r="4" fill="#fff0c8"/><path d="M157 52H174Q171 39 181 39Q191 39 188 52H205V68Q217 65 217 75Q217 85 205 82V99H157Z" fill="#dfac58"/><path d="M222 48H259V91H222V78Q210 82 210 72Q210 62 222 66Z" fill="#53bc9d"/></svg><span lang="he" dir="rtl">חשב · מחשבה</span>';panel.append(meaning);
   if(world){const owned=control(panel,'המכונה שלך בסדנה',worldPicture(world,true)+glyph('map')+rewardTrail(world),()=>{close();onWorld?.();},'world-preview');owned.classList.toggle('temporary',!!world.problem);}control(panel,'הדגמה חוזרת',glyph('build')+glyph('next'),()=>{newAttempt();render();},'primary');
  }
  if(error){const msg=document.createElement('p');msg.setAttribute('role','alert');msg.setAttribute('aria-label',error);msg.innerHTML=glyph('retry')+glyph(phase==='BUILD'?'power':'sound');panel.append(msg);}
  control(panel,'חזרה לסדנה',glyph('back'),close,'challenge-back');const credit=document.createElement('small');credit.className='audio-credit';credit.innerHTML='<a href="https://commons.wikimedia.org/wiki/File:En-us-thought.ogg" target="_blank" rel="noopener">Audio: Dvortygirl</a> · <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noopener">CC BY-SA 3.0</a> · WAV conversion';panel.append(credit);
  const focus=[...panel.querySelectorAll('button:not(:disabled)')].find(b=>b.getAttribute('aria-label')===previousFocus)||panel.querySelector('.run-challenge:not(:disabled)')||panel.querySelector('button:not(:disabled)');focus?.focus({preventScroll:true});
 }
 function close(){stop();panel.hidden=true;app.hidden=false;afterClose?.();launch.focus({preventScroll:true});}
 launch.onclick=()=>{beforeOpen?.();newAttempt();app.hidden=true;panel.hidden=false;render();};document.addEventListener('visibilitychange',()=>{if(document.hidden&&!panel.hidden){stop();error='הפעילות הושהתה. לחצו על הרמקול כדי להמשיך.';render();}});window.addEventListener('pagehide',stop);return {open:()=>launch.click(),close};
}
