import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {MachineSession} from './session-controller.mjs';import {mappings} from './learning-content.mjs';import {PilotStorage,STORAGE_KEY} from './storage.mjs';import {Rewards} from './rewards.mjs';
const spec=JSON.parse(readFileSync(new URL('./learning-model.spec.json',import.meta.url)));let time=1000;
const make=snapshot=>new MachineSession(spec,{clock:()=>time,random:()=>0,snapshot});
const intro=s=>{s.start();s.teachHeard(mappings[0]);s.teachHeard(mappings[1]);};
const answer=s=>{if(s.phase==='TEACH')s.teachHeard(s.teachingItem());for(const id of s.task.options)s.heardAudio(id);s.choose(s.task.itemId);if(s.task.family==='letter_to_sound')s.confirm();};
const complete=s=>{while(s.phase!=='COMPLETE'){answer(s);s.next();}};
class Memory {constructor(){this.data=new Map();this.keys=[];this.fail=false;}getItem(k){this.keys.push(k);return this.data.get(k)??null;}setItem(k,v){this.keys.push(k);if(this.fail)throw Error('quota');this.data.set(k,v);}removeItem(k){this.keys.push(k);this.data.delete(k);}}
test('single settlement, reload on success and same feedback cannot double coins or evidence',()=>{const s=make();intro(s);answer(s);assert.equal(s.rewards.state.coins,2);const restored=make(s.snapshot());assert.deepEqual(restored.engine.inspect(),s.engine.inspect());assert.equal(restored.choose(restored.task.itemId),false);assert.equal(restored.rewards.state.coins,2);restored.rewards.settle(restored.lastEvent);assert.equal(restored.rewards.state.coins,2);});
test('first error/help survive reload and pay one coin on correction',()=>{const s=make();intro(s);s.heardAudio(s.task.itemId);s.choose(s.task.options.find(x=>x!==s.task.itemId));const r=make(s.snapshot());assert.equal(r.phase,'ERROR');r.correction();r.heardAudio(r.task.itemId);r.choose(r.task.itemId);assert.equal(r.lastEvent.independent,false);assert.equal(r.lastEvent.weight,0);assert.equal(r.rewards.state.coins,1);const helped=make();intro(helped);helped.help();const h=make(helped.snapshot());assert.equal(h.phase,'SUPPORT');assert.equal(h.engine.inspect().pending.supported,true);});
test('refresh preserves options but clears uncommitted selected answer and listening',()=>{const s=make();intro(s);s.engine.abandon(s.encounter);s.open(mappings[0],'letter_to_sound',true);for(const id of s.task.options)s.heardAudio(id);s.choose(s.task.itemId);const saved=s.snapshot();assert.equal(Object.hasOwn(saved.session,'selected'),false);const r=make(saved);assert.deepEqual(r.task.options,s.task.options);assert.equal(r.selected,null);assert.equal(r.confirm(),false);assert.equal(r.choose(r.task.itemId),false);});
test('four connections give eight coins, two distinct purchases are idempotent and cannot alter learning',()=>{const s=make();intro(s);complete(s);assert.equal(s.rewards.state.coins,8);const learning=s.engine.inspect();assert.equal(s.buyPart('fan'),true);assert.equal(s.rewards.state.coins,4);assert.equal(s.buyPart('fan'),true);assert.equal(s.rewards.state.coins,4);assert.equal(s.buyPart('paddle'),true);assert.equal(s.rewards.state.coins,0);assert.equal(s.buyPart('unknown'),false);assert.deepEqual(s.engine.inspect(),learning);const r=make(s.snapshot());assert.deepEqual(r.rewards.state,s.rewards.state);assert.equal(r.buyPart('fan'),true);assert.equal(r.rewards.state.coins,0);});
test('explicit finish preserves machine, continue creates a new round/encounter without autoplay',()=>{const s=make();intro(s);complete(s);s.finish();const r=make(s.snapshot());assert.equal(r.phase,'FINISHED');assert.equal(r.continueRound(),false);r.reopen();const before=r.engine.inspect().sequence;r.continueRound();assert.equal(r.connections,0);assert.equal(r.round,2);assert.equal(r.task.family,'letter_to_sound');assert.ok(r.encounter>before);assert.equal(r.rewards.state.coins,8);assert.equal(r.heard.size,0);});
test('pause, teaching midway and review debt are replayable without manufactured mastery',()=>{const s=make();s.start();s.teachHeard(mappings[0]);const r=make(s.snapshot());assert.equal(r.teachingItem(),mappings[1]);r.teachHeard(mappings[1]);r.help();r.pause();const p=make(r.snapshot());assert.equal(p.phase,'PAUSED');p.resume();assert.equal(p.phase,'SUPPORT');assert.equal(p.engine.report(mappings[0]).gates.M1,false);});
test('save is one atomic write, only dedicated key, and storage failure is explicit',()=>{const mem=new Memory();mem.setItem('ebr-profile-v2','unchanged');mem.keys=[];const store=new PilotStorage(mem);assert.equal(store.load(),null);const s=make();intro(s);assert.equal(store.save({machine:s.snapshot(),prefs:{reduced:false}}),true);answer(s);mem.fail=true;assert.equal(store.save({machine:s.snapshot(),prefs:{reduced:false}}),false);assert.equal(store.problem,'unavailable');const disk=new PilotStorage(mem).load();assert.equal(make(disk.machine).rewards.state.coins,0);mem.fail=false;store.save({machine:s.snapshot(),prefs:{reduced:false}});assert.equal(make(new PilotStorage(mem).load().machine).rewards.state.coins,2);assert.ok(mem.keys.every(k=>k===STORAGE_KEY));assert.equal(mem.data.get('ebr-profile-v2'),'unchanged');});
test('two tabs detect conflict without overwriting; refresh can load latest snapshot',()=>{const mem=new Memory(),a=new PilotStorage(mem),b=new PilotStorage(mem);a.load();b.load();a.save({machine:make().snapshot(),prefs:{reduced:false}});assert.equal(b.save({machine:make().snapshot(),prefs:{reduced:true}}),false);assert.equal(b.problem,'conflict');assert.equal(new PilotStorage(mem).load().prefs.reduced,false);});
test('malformed/future storage remains untouched until explicit reset',()=>{for(const raw of ['{broken',JSON.stringify({schemaVersion:2,revision:1,snapshot:{}})]){const mem=new Memory();mem.setItem(STORAGE_KEY,raw);const storage=new PilotStorage(mem);assert.equal(storage.load(),null);assert.equal(storage.problem,'invalid');assert.equal(storage.save({}),false);assert.equal(mem.getItem(STORAGE_KEY),raw);assert.equal(storage.reset(),true);assert.equal(mem.getItem(STORAGE_KEY),null);}});
test('bad session/reward/journal snapshots are rejected instead of silently repaired',()=>{const s=make();intro(s);const snapshot=s.snapshot();for(const mutate of [x=>x.session.connections=5,x=>x.rewards.coins=100,x=>x.learning.push({method:'respond',args:[999,true],time:1000}),x=>x.session.phase='UNKNOWN',x=>x.session.task.options=['RZ-G-M','RZ-G-N']]){const bad=structuredClone(snapshot);mutate(bad);assert.throws(()=>make(bad));}assert.throws(()=>new Rewards({coins:3,settled:{},owned:[],part:null}));});

test('denied storage reads allow explicit temporary play without claiming corrupt data',()=>{const store=new PilotStorage({getItem(){throw Error('denied');},setItem(){throw Error('denied');}});assert.equal(store.load(),null);assert.equal(store.problem,'unavailable');assert.equal(store.blocked,false);assert.equal(store.save({}),false);});
