import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {MachineSession} from './session-controller.mjs';import {mappings} from './learning-content.mjs';import {AudioPlayer} from './audio-player.mjs';
const spec=JSON.parse(readFileSync(new URL('./learning-model.spec.json',import.meta.url)));
const make=()=>new MachineSession(spec,{random:()=>0,clock:()=>1000});
function intro(s){s.start();s.teachHeard(mappings[0]);s.teachHeard(mappings[1]);}
function pass(s){if(s.phase==='TEACH')s.teachHeard(s.teachingItem());const id=s.task.itemId;s.heardAudio(id);s.choose(id);s.next();}
test('four complete connections, no extra connection or manufactured word gate',()=>{const s=make();intro(s);for(let i=0;i<4;i++)pass(s);assert.equal(s.phase,'COMPLETE');assert.equal(s.connections,4);assert.equal(s.choose(mappings[0]),false);assert.equal(s.next(),false);assert.equal(s.engine.report('novel_word_decoding').status,'unassessed');assert.equal(s.engine.availableActivities().some(t=>t.itemId.startsWith('RZ-W')),false);});
test('silent answer and passive/double teaching cannot advance',()=>{const s=make();intro(s);assert.equal(s.choose(s.task.itemId),false);assert.equal(s.connections,0);assert.equal(s.teachHeard(mappings[0]),false);s.heardAudio(s.task.itemId);s.choose(s.task.itemId);s.choose(s.task.itemId);assert.equal(s.connections,1);});
test('help is recorded before answer; completed support builds but does not grant mastery',()=>{const s=make();intro(s);s.help();s.heardAudio(s.task.itemId);s.choose(s.task.itemId);assert.equal(s.lastEvent.independent,false);assert.equal(s.lastEvent.weight,0);assert.equal(s.connections,1);assert.equal(s.engine.report(mappings[0]).gates.M1,false);});
test('first error persists, correction then different independent retry after three other responses',()=>{const s=make();intro(s);s.heardAudio(s.task.itemId);s.choose(s.task.options.find(x=>x!==s.task.itemId));assert.equal(s.phase,'ERROR');s.correction();s.choose(s.task.itemId);assert.equal(s.lastEvent.weight,0);s.next();for(let i=0;i<3;i++)pass(s);assert.equal(s.task.family,'letter_to_sound');assert.equal(s.task.itemId,mappings[0]);for(const id of s.task.options){s.optionAudio(id);s.heardAudio(id);}s.choose(s.task.itemId);s.confirm();assert.equal(s.lastEvent.independent,true);assert.equal(s.lastEvent.weight,1);s.next();assert.equal(s.phase,'COMPLETE');assert.equal(s.connections,4);assert.equal(s.engine.inspect().outcomes[0].correct,false);});
test('audio choices require both listening and a separate confirmation',()=>{const s=make();intro(s);s.engine.abandon(s.encounter);s.open(mappings[0],'letter_to_sound',true);assert.equal(s.choose(s.task.itemId),false);for(const id of s.task.options)s.heardAudio(id);s.choose(s.task.itemId);assert.equal(s.phase,'PROMPT');assert.equal(s.engine.inspect().outcomes.length,0);s.confirm();assert.equal(s.phase,'SUCCESS');});
test('pause/resume preserves support and pending encounter',()=>{const s=make();intro(s);s.help();const id=s.encounter;s.pause();assert.equal(s.choose(s.task.itemId),false);s.resume();assert.equal(s.phase,'SUPPORT');assert.equal(s.encounter,id);s.heardAudio(s.task.itemId);s.choose(s.task.itemId);assert.equal(s.lastEvent.weight,0);});
class FakeAudio {constructor(){this.duration=1;this.currentTime=0;}play(){return Promise.resolve();}pause(){this.onpause?.();}removeAttribute(){}load(){}}
test('audio cancels old playback and never reports stale success',async()=>{const audios=[];const player=new AudioPlayer({create:()=>{const a=new FakeAudio();audios.push(a);return a;}});const first=player.play(mappings[0]);const second=player.play(mappings[1]);assert.equal(await first,false);audios[0].onended();audios[1].onended();assert.equal(await second,true);player.stop();});
test('audio failure reports failure without teaching completion',async()=>{let errors=0,a;const player=new AudioPlayer({create:()=>a=new FakeAudio(),onError:()=>errors++});const done=player.play(mappings[0]);a.onerror();assert.equal(await done,false);assert.equal(errors,1);});
test('three supported errors offer accessible familiar practice instead of endless correction',()=>{const s=make();intro(s);s.heardAudio(s.task.itemId);const wrong=s.task.options.find(x=>x!==s.task.itemId);s.choose(wrong);for(let i=0;i<3;i++){s.correction();s.choose(wrong);}assert.equal(s.phase,'REST');s.familiar();assert.equal(s.task.family,'visual_match');s.choose(s.task.itemId);assert.equal(s.connections,1);assert.equal(s.lastEvent.weight,0);});
